export default function (
    /** @type {import('plop').NodePlopAPI} */
    plop
) {
    plop.setGenerator('example-1', {
        description: 'First example generator',
        prompts: [
            {
                type: 'input',
                name: 'heading',
                message: 'Please provide a heading'
            },
        ],
        actions: [
            {
                type: 'add',
                path: 'example-output/example-1-{{kebabCase heading}}.js',
                templateFile: 'example-templates/example-1.hbs'
            },
        ],
    });

    plop.setGenerator('example-2', {
        description: 'Second example generator',
        prompts: [
            {
                type: 'list',
                name: 'lang',
                message: 'Please provide a language code',
                choices: [
                    { name: 'English', value: 'en' },
                    { name: 'British English', value: 'en-GB' },
                    { name: 'US English', value: 'en-US' },
                    { name: 'Arabic', value: 'ar' },
                    { name: 'Spanish', value: 'es' },
                    { name: 'French', value: 'fr' },
                    { name: 'Portuguese', value: 'pt' },
                    { name: 'Chinese', value: 'zh' },
                ],
            },
            {
                type: 'input',
                name: 'heading',
                message: 'Please provide a heading',
            },
            {
                type: 'input',
                name: 'description',
                message: 'Please provide a short description',
                default: 'Generated by example-2',
            },
        ],
        actions: [
            {
                type: 'add',
                path: 'example-output/example-2-{{kebabCase heading}}/index.html',
                templateFile: 'example-templates/example-2/html.hbs',
                force: true, // overwrite file if it exists
            },
            {
                type: 'add',
                path: 'example-output/example-2-{{kebabCase heading}}/script.js',
                templateFile: 'example-templates/example-2/script.hbs',
                force: true,
            },
            {
                type: 'add',
                path: 'example-output/example-2-{{kebabCase heading}}/style.css',
                templateFile: 'example-templates/example-2/style.hbs',
                force: true,
            },
        ],
    });
};
